### ISSUE TITLE
Unable to uninstall ShadowBird

### ISSUE THREAD

**Issue by ajvsol** [overdodactyl/ShadowBird#15]
After #14 I disabled the Dark theme to try to get my email folder readable again - no dice. 

Then I deleted the chrome folder too - that didn't help either. How do I fully uninstall ShadowBird?

**Comment by overdodactyl** [comment]
Deleting the chrome folder, removing any changes you made to `user.js` (or in your preferences to alter text area backgrounds), and restarting Thunderbird should take care of it.

**Comment by ajvsol** [comment]
Ah okay, it seems I deleted the chrome folder in the main Thunderbird folder instead of the Profile folder.
