### ISSUE TITLE
Add dark theme to the calendar

### ISSUE THREAD

**Issue by 2xninja** [overdodactyl/ShadowBird#5]
*Add-ons Manager, Tasks etc.

System: Windows 10 Pro, Build 10.0.16299, Thunderbird 60.2.1 (32-bit)

**Comment by overdodactyl** [comment]
Hi @somethingsomehing - thanks for opening the issue.

I've just added support for most of the `about:pages` (addons, support, etc.):

<img width="1080" alt="screen shot 2018-10-10 at 4 21 08 pm" src="https://user-images.githubusercontent.com/33071129/46769522-560c8300-cca9-11e8-9b06-97f3f448fbdd.png">

<img width="1080" alt="screen shot 2018-10-10 at 4 21 30 pm" src="https://user-images.githubusercontent.com/33071129/46769530-5d339100-cca9-11e8-9204-d2a84f664bc5.png">

I think it will be most helpful to have a unique issue for each feature/page that isn't styled, so I'm going to rename this issue and let this one be focused on the calendar window.  

Feel free to open additional issues for other windows you run across.

**Comment by overdodactyl** [comment]
I've add styling for the tasks and calendar sections.  I don't use either of these features very often, so if you notice any issues, please open up a new issue.

<img width="1181" alt="screen shot 2018-10-10 at 8 13 44 pm" src="https://user-images.githubusercontent.com/33071129/46776512-23728280-ccc9-11e8-8ac6-32a26378c37d.png">

<img width="1181" alt="screen shot 2018-10-10 at 8 13 34 pm" src="https://user-images.githubusercontent.com/33071129/46776518-2d948100-ccc9-11e8-903c-555033cf0de2.png">

**Comment by 2xninja** [comment]
Just updated to latest it looks great man.
